name: Linux build qt6

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - 'updater/**'
      - 'windows/**'
      - 'macos-build/**'
      - '!.github/workflows/linux qt6.yml'

  pull_request:
    branches: [ master ]

    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/**'
      - 'macos-build/**'
      - '!.github/workflows/linux qt6.yml'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      QT_PREFIX: "/home/runner/work/writernote-qt/writernote-qt/qt_install/"
      PREFIX_LIB: "/home/runner/work/writernote-qt/writernote-qt/3rdparty/"

    steps:
      - name: Clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Run a one-line script
        run: |
          sudo apt update
          sudo apt -y install libzip-dev
          sudo apt -y install libfreetype-dev libfontconfig1-dev 
          sudo apt -y install libtiff-dev libnss3-dev libcairo2-dev
          sudo apt -y install libboost-all-dev libopenjp2-7-dev
          sudo snap install cmake --classic
          sudo apt -y install ninja-build

          sudo apt install -y libdbus-1-dev libegl-dev libfontconfig1-dev libfreetype-dev libglib2.0-dev libglx-dev libgtk-3-dev libharfbuzz-dev libice-dev
          sudo apt install -y libicu-dev libopengl-dev libpcre2-dev libpng-dev libsm-dev libssl-dev libwayland-dev
          sudo apt install -y libx11-dev libx11-xcb-dev libxcb1-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev 
          sudo apt install -y libxcb-render0-dev libxcb-render-util0-dev libxcb-shape0-dev libxcb-shm0-dev
          sudo apt install -y libxcb-sync-dev libxcb-util-dev libxcb-xfixes0-dev libxcb-xkb-dev libxcursor-dev libxkbcommon-dev libxkbcommon-x11-dev zlib1g-dev

      - name: Qt 6 cache.
        if: false
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ${{ env.PREFIX_LIB }}/qt-cache
          key: ${{ runner.OS }}-qt6-${{ env.CACHE_KEY }}-qtmulmedia-0

      - name: Use cached Qt 6.2.4.
        if: steps.cache-qt.outputs.cache-hit == 'true'
        run: |
          cd $PREFIX_LIB
          mv qt-cache Qt-6.2.4
          sudo mkdir -p $QT_PREFIX
          sudo mv -f Qt-6.2.4 "$(dirname "$QT_PREFIX")"/

      - name: Build Qt 6.2.4
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: |
          git clone -b v6.2.4 https://code.qt.io/qt/qt5.git qt_6_2_4
          cd qt_6_2_4
          perl init-repository --module-subset=qtbase,qtsvg,qtmultimedia,qtshadertools
          
          mkdir -p $QT_PREFIX

          cmake . \
            -DCMAKE_INSTALL_PREFIX=$QT_PREFIX \
            -GNinja

          #./configure \
          #  -prefix $(pwd)/../qt_install \
          #  -libdir $(pwd)/../qt_install \
          #  -release \
          #  -opensource \
          #  -confirm-license \
          #  -nomake tools \
          #  -nomake examples \
          #  -nomake tests \
          #  -skip qtwebengine

          cmake --build .
          cmake --install .

          cp -r $QT_PREFIX $PREFIX_LIB/qt-cache

      - name: Build poppler
        run: |
          echo $(pwd)
          cd 3rdparty/poppler

          export INSTALL_POPPLER=$PREFIX_LIB/poppler/install
          mkdir -p $INSTALL_POPPLER

          mkdir install
          
          cmake . \
            -DCMAKE_INSTALL_LIBDIR=$INSTALL_POPPLER \
            -DCMAKE_INSTALL_INCLUDEDIR=$INSTALL_POPPLER \
            -DQt6_DIR=$QT_PREFIX/lib/cmake/Qt6/
            
          make -j$(nproc)
          sudo make install

      - name: Writernote compile
        run: |
          
          cmake . \
            -DQt6_DIR=$QT_PREFIX/lib/cmake/Qt6/
          
          make -j$(nproc) 
